site_name: ReadTheDocs Dropdown
theme: readthedocs-dropdown
pages:
    
    - User Guide:
        - Custom themes: user-guide/custom-themes.md
        - Plugins: user-guide/plugins.md
    - About:
        - Release Notes: about/release-notes.md
        - Contributing: about/contributing.md
        - License: about/license.md

google_analytics: ['UA-10006093-5', 'readthedocs.sheets.ch']
